### ISSUE TITLE
.infoの衝突

### ISSUE THREAD

**Issue by okc37** [nakajmg/PixelGuide#2]
PixelGuideが有効な状態で閲覧中のhtmlページ内に .info というclass名が出てくると下記CSSが適用されてしまいます。
`
.info {
width: 50px;
height: 25px;
line-height: 25px;
text-align: center;
position: relative;
font-size: 13px;
background-color: rgb(238, 238, 238);
border: 1px solid rgb(204, 204, 204);
border-image-source: initial;
border-image-slice: initial;
border-image-width: initial;
border-image-outset: initial;
border-image-repeat: initial;
color: rgb(51, 51, 51);
}
`

参考
http://www.d-laboweb.jp/event/report/140204.html

**Comment by nakajmg** [comment]
報告ありがとうございます。
元のページのCSSと拡張のCSSが相互に影響を与えてしまう現象は認識しています。
現在クラス名が衝突しないように書き換えていますので、更新をお待ちいただければと思います。
